### ISSUE TITLE
Center for Humane Technology tweet

### ISSUE THREAD

**Issue by Francescaminelli** [mozillach/tweets#193]
### Content Description
We want to publicize a Hacks Bogpost that talks about the partnership between Mozilla and the Center for Humane Technology. We also want to encourage people to take a new course on how to be a Humane technologist. We believe that Mozillians would be interested in this new course. 

### Content
Mozilla partnered with the Center for Humane Technology, a  nonprofit organization that supports Mozilla's efforts for a safe and open web. Read more about this and check out a free course on the challenges of being a humane technologist #mozillacommunity https://mzl.la/38rTYVM

**Comment by MichaelKohler** [comment]
Thanks for filing this. Looks good to me!
