### ISSUE TITLE
Firefox translations Campaign

### ISSUE THREAD

**Issue by Francescaminelli** [mozillach/tweets#195]
### Content Description

Invite to people to test Firefox Translations, with the link to the campaign page

### Content

Help us test Firefox Translations! This new web extension translates web pages directly in Firefox and protects your privacy. Start testing here: [https://mzl.la/3Lkjzxx](https://t.co/DEdlJUwoma) [#mozillacommunity](https://twitter.com/hashtag/mozillacommunity?src=hashtag_click)

**Comment by MichaelKohler** [comment]
Looks good to me! Thanks!

**Comment by MichaelKohler** [comment]
Fixed tweet without raw markdown: https://twitter.com/MozillaCH/status/1528838560471719936

**Comment by Francescaminelli** [comment]
thanks!
